### ISSUE TITLE
dbr prefix error

### ISSUE THREAD

**Issue by pmirla** [framester/Framester#1]
Hi, While I was trying this example, there was an error. probably the query is incomplete. Any suggestions on how to fix this? 

This is an example from your documentation.
PREFIX fschema: <https://w3id.org/framester/schema/>
 PREFIX frame: <https://w3id.org/framester/framenet/abox/frame/> 
 SELECT DISTINCT ?frame ?dbr 
 WHERE { 
  ?frame fschema:playsRoleIn frame:Text . 
 }

Virtuoso 37000 Error SP031: SPARQL compiler: Variable 'dbr' is used in the query result set but not assigned

**Comment by alammehwish** [comment]
Hi, if you read the error very carefully, it is not hard to resolve, you just need to remove the variable "?dbr" and it works. It is a typo, I have edited it in the documentation also.

**Comment by pmirla** [comment]
Thank you. I wanted to ask few questions on commercial usage, what would be the best email to reach at? Thanks

**Comment by alammehwish** [comment]
All the contact information have been provided on the home page as mentioned in the "Readme.md" . Please select any of them and send your questions. Thanks.
