### ISSUE TITLE
Impossible to get the data

### ISSUE THREAD

**Issue by Shimorina** [framester/Framester#4]
Hello,

When I try to download the data via lfs, the following error message is shown to me:
```This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.```

Thank you for looking into this!

**Comment by luigi-asprino** [comment]
Hi,

you can download the latest Framester’s dump from here http://framester.istc.cnr.it/framester-data-4.0.0.nq.gz

**Comment by Robbe7730** [comment]
@luigi-asprino that link doesn't seem to work anymore, is there another way to get the data? Thanks in advance :slightly_smiling_face:

**Comment by luigi-asprino** [comment]
It should be available again. Sorry for the inconvenience.

**Comment by Robbe7730** [comment]
Thanks for the reply! However, I still get a 404 on <http://framester.istc.cnr.it/framester-data-4.0.0.nq.gz>.

**Comment by luigi-asprino** [comment]
This is strange.. have you tried to wipe the browser's cache? I'm able to download it from my mobile

**Comment by Robbe7730** [comment]
yes, even using `wget` or `curl` gives me 404.

**Comment by Robbe7730** [comment]
I have found the issue, it was still redirecting me to <http://framester.istc.cnr.it/blazegraph/framester-data-4.0.0.nq.gz> instead of <http://framester.istc.cnr.it/framester-data-4.0.0.nq.gz> and I used that URL with curl too. Using the second one works, sorry for the inconvenience.

**Comment by luigi-asprino** [comment]
No problem.
Happy you are able to download it.

Il sab 8 gen 2022, 12:48 Robbe Van Herck ***@***.***> ha
scritto:

**Comment by Claus1** [comment]
Again impossible to download,  http://framester.istc.cnr.it/blazegraph/framester-data-4.0.0.nq.gz ? http://framester.istc.cnr.it/framester-data-4.0.0.nq.gz are wrong.
